export const POKEMON_LOADING = "POKEMON_LOADING";
export const POKEMON_SUCCESS = "POKEMON_SUCCESS";
export const POKEMON_ERROR = "POKEMON_ERROR";

export const POKEMON_DETAILS_LOADING = "POKEMON_DETAILS_LOADING";
export const POKEMON_DETAILS_SUCCESS = "POKEMON_DETAILS_SUCCESS";
export const POKEMON_DETAILS_ERROR = "POKEMON_DETAILS_ERROR";

export const ADD_TO_FAVOURITES = "ADD_TO_FAVOURITES";
export const REMOVE_FROM_FAVOURITES = "REMOVE_FROM_FAVOURITES";
